name = "focusrecipe"
compatibility_date = "2025-10-29"

[assets]
directory = "./dist"
binding = "ASSETS"

[build]
command = "npm run build"
cwd = "."

# Environment variables for Cloudflare Pages
[env.production]
name = "focusrecipe-production"

[env.preview]
name = "focusrecipe-preview"
