name = "focusrecipe"
compatibility_date = "2025-10-29"

[assets]
directory = "./dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "focusrecipe-production"

[env.preview]
name = "focusrecipe-preview"
